apiVersion: v1
kind: Service
metadata:
  name: relayground
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: relayground
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
