apiVersion: apps/v1
kind: Deployment
metadata:
  name: Tes3MP Server Depolyment
  labels:
    app: tes3mp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tes3mp
  template:
    metadata:
      labels:
        app: tes3mp
    spec:
      containers:
        - name: tes3mp
          image: tes3mp/server
          ports:
            - containerPort: 25565
