apiVersion: v1
kind: Pod
metadata:
  name: tes3mp
  labels:
    name: tes3mp
spec:
  containers:
    - name: tes3mp
      image: tes3mp/server:0.8.1
      resources:
        limits:
          memory: "2G"
          cpu: "800m"
      ports:
        - containerPort: 25565
