apiVersion: v1
kind: Service
metadata:
  name: tes3mp
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: tes3mp
  ports:
    - protocol: UDP
      port: 25565
      targetPort: 25565
