name: "Deploy to Kubernetes"
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/k8s-publish.yml"
      - "manifests/**/*.yml"
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      reg_pfx: "rground"
      resource_group: "rg"
      cluster_name: "rg"
    steps:
      - uses: actions/checkout@master

      # Log into docker registry fro relayground
      - uses: Azure/docker-login@v1
        with:
          login-server: ${{ env.reg_pfx }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Log into azure
      - uses: Azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: ${{ env.cluster_name }}
          resource-group: ${{ env.resource_group }}

      - uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
            manifests/tes3mp.yml
