name: "Deploy to Kubernetes"
on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/k8s-publish.yml"
      - "manifests/**/*.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      reg_pfx: "relayground"
    steps:
      - uses: actions/checkout@master
      - uses: Azure/docker-login@v1
        with:
          login-server: ${{ env.reg_pfx }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
