name: "Relayground"
on:
  push:
    branches: "main"
    paths:
      - "packages/relayground/**/*"
      - "package*.json"
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-20.04
    env:
      reg: "{{ secrets.ACR_REG_PFX}}.azurecr.io"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

  az-login:
    runs-on: ubuntu-20.04
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Log into docker registry for relayground
      - uses: Azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REG }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - uses: Azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: ${{ secrets.AZ_CLUSTER }}
          resource-group: ${{ secrets.AZ_RESOURCE_GROUP }}

  build:
    runs-on: ubuntu-20.04
    needs: [setup]
    env:
      appname: "relayground"
      region: "north central us"
    steps:
      - run: |
          TAG="${{ secrets.ACR_REG }}/${{env.appname}}:latest"
          docker build . -t ${TAG} -f containers/${{env.appname}} -o type=docker
          docker push ${TAG}

  deploy:
    needs: [build, az-login]
    runs-on: ubuntu-20.04
    steps:
      - uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
            manifests/relayground.yml
            manifests/relayground-balancer.yml
