name: "Deploy to Kubernetes"
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/k8s-publish.yml"
      - "manifests/**/*.yml"
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # Log into azure
      - uses: Azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: ${{ secrets.AZ_CLUSTER }}
          resource-group: ${{ secrets.AZ_RESOURCE_GROUP }}

      - uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
            manifests/tes3mp.yml
            manifests/tes3mp-balancer.yml
